//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaRopa
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtprenda
    {
        public int id_prenda { get; set; }
        public string tipo { get; set; }
        public string marca { get; set; }
        public int talla { get; set; }
        public string color { get; set; }
        public decimal precio { get; set; }
    }
}
